---


- name: Update package repository
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started

- name: Enable Nginx service on boot
  service:
    name: nginx
    enabled: yes


- name: Make a backup copy of Nginx default file
  ansible.builtin.copy:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-available/default.old
    force: no
    remote_src: yes

- name: Configure Nginx to server as a reverse proxy
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

