---
# tasks file for nginx

- name: Update package repository
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started

- name: Enable Nginx service on boot
  service:
    name: nginx
    enabled: yes
