# haproxy/tasks/main.yml
---
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  become: yes

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  become: yes
  notify: Restart HAProxy

- name: Ensure HAProxy is running
  systemd:
    name: haproxy
    state: started
    enabled: yes
  become: yes

