---
  - name: Create project directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: ope
      group: ope
      mode: 2755
    loop:
      - /var/www/html/login
      - /var/www/html/login/config
      - /var/www/html/login/models
      - /var/www/html/login/routes
      - /var/www/html/login/static
      - /var/www/html/login/static/images
      - /var/www/html/login/static/js