---
  - name: Move imgage templates to /var/www/html/login/static/images
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /var/www/html/login/static/images/
    loop:
      - files/akara.jpeg
      - files/amala-and-ewedu.jpeg
      - files/boli-and-fish.jpeg
      - files/egusi-soup.jpeg
      - files/jollof.jpeg
      - files/moin-moin.jpeg
      - files/ofada-rice.jpeg
      - files/pounded-yam-and-egusi.jpeg
      - files/tuwo-shinkafa.jpeg