---
  - name: Creating group 'mihamm'
    ansible.builtin.group:
      name: "{{ user_mm }}"
      state: present

  - name: Creating user 'mihamm' with sudo access
    ansible.builtin.user:
      name: "{{ user_mm }}"
      create_home: yes
      shell: /bin/bash
      groups: mihamm,sudo

  - name: Create .ssh directory if it doesn't exist
    ansible.builtin.file:
      path: '/home/{{ user_mm }}/.ssh'
      state: directory
      mode: 0700
      owner: "{{ user_mm }}"
      group: "{{ user_mm }}"
  
  - name: Copying SSH public key to gcp
    ansible.posix.authorized_key:
      user: "{{ user_mm }}"
      state: present
      key: "{{ mm_key }}"