---
  - name: Creating group 'tunde'
    ansible.builtin.group:
      name: "{{ user_tunde }}"
      state: present

  - name: Creating user 'tunde' with sudo access
    ansible.builtin.user:
      name: "{{ user_tunde }}"
      create_home: yes
      shell: /bin/bash
      groups: tunde,sudo

  - name: Create .ssh directory if it doesn't exist
    ansible.builtin.file:
      path: '/home/{{ user_tunde }}/.ssh'
      state: directory
      mode: 0700
      owner: "{{ user_tunde }}"
      group: "{{ user_tunde }}"
  
  - name: Copying SSH public key to gcp
    ansible.posix.authorized_key:
      user: "{{ user_tunde }}"
      state: present
      key: "{{ tunde_key }}"