---
- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'

- name: Copy Prometheus configuration file
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'



- name: Configure Prometheus to scrape application metrics
  copy:
    content: |
      scrape_configs:
        - job_name: 'nodejs_app'
          static_configs:
            - targets: ['localhost:3000']
    dest: /etc/prometheus/prometheus.yml
