---
  - name: Back up the config file
    ansible.builtin.copy:
      src: /etc/filebeat/filebeat.yml
      dest: /etc/filebeat/filebeat.yml.old
      force: no
      remote_src: yes

  - name: Override the config file
    ansible.builtin.template:
      src: filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
      