---
  
  - name: Update package repository cache
    ansible.builtin.package:
      update_cache: yes

  - name: Import all filebeat task files
    ansible.builtin.include_tasks: "{{ item }}"
    loop:
      # - filebeat-repo.yml
      # - install.yml
      - filebeat-config.yml
      # - copy-el-cert.yml
      # - module.yml
      # - service.yml
      - setup.yml
      - test-config.yml
      - test-output.yml


      

    
